Added memory sequence minigame
RichardLam772001/cs375 pull request #108
Opened 2023-08-28 19:20 UTC by MattWu28

Added sequence memory mini-game. The layer must select the five randomly chosen tiles in the order shown to succeed. Static green tiles indicate completion while flashing red tiles followed by a repetition of the sequence indicates an incorrect player input.

2023-08-31 20:29 UTC, ColinJPage requested changes
Mostly optional nitpicks. Try experimenting with the constants to increase the pacing of the minigame to like 5-8 seconds

2023-08-31 20:29 UTC, ColinJPage commented on app/game/memoryGame/index.html
> +        </tbody>
The grid is hard-coded as 3x3, which seems perfectly fine. I'd suggest adding elements these dynamically, but it's not necessary

2023-08-31 20:29 UTC, ColinJPage commented on app/game/memoryGame/script.js
> +canvas8 = document.getElementById("canvas8");
Would there be anything else with id "canvasX"? I think a more descriptive Id could help

2023-08-31 20:29 UTC, ColinJPage commented on app/game/memoryGame/script.js
> +let pattern = [0, 0, 0, 0, 0];
Let `patternLength` be a constant

2023-08-31 20:29 UTC, ColinJPage commented on app/game/memoryGame/script.js
> +        }, 1200 * i);
Let's pull these values into named constants at the top of the file.
Something like `blinkDuration` and `timeBetweenBlinks`.
I also think we should lower these values to be pretty quick. The whole minigame should take like 5 seconds ideally

2023-08-31 20:29 UTC, ColinJPage commented on app/game/memoryGame/script.js
> +    }, 6000);
`timeBetweenBlinks * patternLength`

2023-08-31 20:29 UTC, ColinJPage commented on app/game/memoryGame/script.js
> +}
Alternatively, we could leave the event listeners attached, and then in `handler()` choose to ignore the click if the sequence is still playing

2023-08-31 20:29 UTC, ColinJPage commented on app/game/memoryGame/script.js
> +        playerPattern.push(curr.number);
Why keep the array `playerPattern`? We could instead keep the index of the current number

2023-08-31 20:29 UTC, ColinJPage commented on app/game/memoryGame/script.js
> +    }, 800);
`incorrectPenaltyTime`

2023-08-31 20:29 UTC, ColinJPage commented on app/game/memoryGame/index.html
> +<body>
Let's put some message container here. We can swap out the text to let the player know what's going on.
`Memorize the pattern...`
`Repeat the pattern:`
`INCORRECT, try again!`
`Breach resolved!`

2023-09-04 20:01 UTC, RichardLam772001 approved these changes

2023-09-04 20:01 UTC, ColinJPage approved these changes

2023-09-04 20:01 UTC, merged