lobby system backend
RichardLam772001/cs375 pull request #73
Opened 2023-08-15 03:03 UTC by langu44

implemented major lobby system functions

some issues with current version of lobby system, can discuss in class some ideas and potential changes

2023-08-16 00:51 UTC, ColinJPage requested changes
Awesome stuff! I have a couple small suggestions, but otherwise I'll be ready to approve :)

2023-08-16 00:51 UTC, ColinJPage commented on app/public/lobby/lobbyfuncs.js
> +		});
Long said every promise needs a catch ;)
Seems a little tedious but it can't hurt

2023-08-16 00:51 UTC, ColinJPage commented on app/public/lobby/lobbyfuncs.js
>  	}).catch((e) => {
If the refresh goes wrong, should we clear the table of lobbies? Or leave up the outdated list?

2023-08-16 00:51 UTC, ColinJPage commented on app/public/lobby/lobbyfuncs.js
>  	});
This code is identical to the code above. I recommend making a `fetchRefresh()` function that is called both by the refresh button and when connecting to the websocket

2023-08-21 19:34 UTC, langu44 commented
im leaving lobby.js in there as backup for now until we confirm there are no issues with this version of the lobby system, ill get rid of it once everything's working

2023-08-21 20:10 UTC, ColinJPage approved these changes
Yup! Looks good

2023-08-21 20:10 UTC, merged